// Intro
export const INTRO_STACK = 'INTRO_STACK';
export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const WELCOME_SCREEN = 'WELCOME_SCREEN';

// LOGIN
export const LOGIN_TABS_SCREEN = 'LOGIN_TABS_SCREEN';
export const LOGIN_OTP_SCREEN = 'LOGIN_OTP_SCREEN';
export const LOGIN_OTP_CODE_SCREEN = 'LOGIN_OTP_CODE_SCREEN';
export const LOGIN_PASSWORD_SCREEN = 'LOGIN_PASSWORD_SCREEN';

// REGISTRATION
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const REGISTER_SUCCESS_SCREEN = 'REGISTER_SUCCESS_SCREEN';

// QUICK LOOK
export const QUICK_VIEW_AGREEMENT = 'QUICK_VIEW_AGREEMENT';
export const QUICK_VIEW_REGISTRATION = 'QUICK_VIEW_REGISTRATION';
export const QUICK_VIEW_REGISTRATION_SUCCESS = 'QUICK_VIEW_REGISTRATION_SUCCESS';
export const QUICK_VIEW_PASSWORD_ENTRANCE_SUCCESS = 'QUICK_VIEW_PASSWORD_ENTRANCE_SUCCESS';

//FORGOT PASSWORD AND USER NAME
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_CHANGED_SUCCESSFULLY = 'FORGOT_PASSWORD_CHANGED_SUCCESSFULLY';
export const FORGOT_USER_NAME = 'FORGOT_USER_NAME';
export const FORGOT_USER_NAME_CHANGED_SUCCESSFULLY = 'FORGOT_USER_NAME_CHANGED_SUCCESSFULLY';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESSFULLY = 'RESET_PASSWORD_SUCCESSFULLY';

// App
export const APP_STACK = 'APP_STACK';
export const HOME_SCREEN = 'HOME_SCREEN';
export const GRID_COMPS_SCREEN = 'GRID_COMPS_SCREEN';
export const CHARTS_SCREEN = 'CHARTS_SCREEN';
